# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Untitled3.o
LINKOBJ  = Untitled3.o
LIBS     = -L"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc "D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/libgomp.dll.a"
INCS     = -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/G/FH-dortmund/winter_semester21-22/dps/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Untitled3.o: Untitled3.cpp
	$(CPP) -c Untitled3.cpp -o Untitled3.o $(CXXFLAGS)
